<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

use App\Models\User;

class MailCreateUser extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public $User;
    public $autoGeneratedPassword;
    public function __construct(User $User, $autoGeneratedPassword)
    {
        $this->User = $User;
        $this->autoGeneratedPassword = $autoGeneratedPassword;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        $User = $this->User;
        $autoGeneratedPassword = $this->autoGeneratedPassword;
        
        return $this->from(appSettingGeneral()['app_email'],appSettingGeneral()['app_name'])
                    ->subject('You have been invited to PMS')
                    ->replyTo(appSettingGeneral()['app_email'], appSettingGeneral()['app_name'])
                    ->view('mail.create-user')
                    ->with([
                        'User' => $User,
                        'autoGeneratedPassword' => $autoGeneratedPassword
                    ]);
    }
}
